# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6595af2f7d285bfe6d2402ba4de059863d0a8039cb4243f7b8aca45d2f703ae5a911d197c7f2a082d405725fabc8f2c35dad4c95f87d7527dd0198cf3c2680d6

test:
  secret_key_base: 469497feee2b12e710534f22d1fd0d67d997c878ba7475c06c817c5de34ff0a0e9c151d1daa548eff41b9c26723d9dcf9dfc4f876e78ddcb890b541115a33b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
